### ISSUE TITLE
optimus.Transform should return an error if given an exhausted table

### ISSUE THREAD

**Issue by jonahkagan** [Clever/optimus#26]
One of the big gotchas with optimus right now is that tables get exhausted after you sink them. If you try to reuse a table that has been sinked, you end up with an empty table, when really this is an erroneous use of a table. It would be useful for debugging purposes if this case failed loudly with an error.

**Comment by azylman** [comment]
This would need to be a breaking interface change because `Transform` doesn't return an error right now. We should also look into how other, similar libraries do this - for example, what happens in `mgo` if you try to use an `Iterator` after it's been exhausted? What happens in `bufio.Scanner` if you try to re-scan after it's been exhausted?

**Comment by jonahkagan** [comment]
Maybe it could be an error in the Sink functions, not Transform?

**Comment by azylman** [comment]
I'm actually not even sure that we can detect this with the current interface for a `Table`. An exhausted table is indistinguishable from an empty table.

Looking at other, similar purpose constructs in Go and other languages, this seems to be expected behavior, so I don't think it's worth changing, especially since it'd need to be breaking:
  * [bufio.Scanner](http://play.golang.org/p/le9Tfcxq75)
  * [Python generators](http://repl.it/dTO)
  * mgo.Iterator
  * Go channels
  * Node.js streams

**Comment by jonahkagan** [comment]
Yeah, it would probably require extending the Table interface. I think it will make for a better experience for developers using the library. I can't think of a good reason to not distinguish empty tables from exhausted tables.

At the very least, it should probably be documented.

**Comment by rgarcia** [comment]
I've seen the `io.EOF` error used to signal an exhausted, iterator-like object in Go, e.g. `json.Decoder`'s `Decode`
